import "./globals.css";

export const metadata = {
  title: "Goody-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-[#faf7f7]">{children}</body>
    </html>
  );
}
